brew "fish"
brew "jq"
brew "fzf"
brew "ffmpeg"
brew "tree"
brew "gh"
brew "ghq"
brew "neovim"
cask "docker-desktop"
cask "clipy"
cask "visual-studio-code"
cask "slack"
cask "google-chrome"
cask "quicklook-json"
cask "1password-cli"
cask "claude"
# cask "gyazo"