- hosts: gce_ubuntu
  user: yuki
  vars:
    username: yuki
    email: niboshiporipori@gmail.com
  roles:
    - role: joshualund.golang
      become: yes
  tasks:
    - name: "apt-get install git"
      apt: pkg=git
      become: yes
    - git_config: name=user.name scope=global value="{{ username }}"
    - git_config: name=user.email scope=global value="{{ email }}"
    - git_config: name=core.editor scope=global value="vim"
    - name: "apt-get install tig"
      apt: pkg=tig
      become: yes
    - name: "apt-get install tmux"
      apt: pkg=tmux
      become: yes
    - name: install fish repo
      apt_repository:
        repo="ppa:fish-shell/release-2"
        state=present
        update_cache=yes
      when: ansible_distribution == "Ubuntu"
    - name: install fish
      apt: name=fish state=present
      become: yes
    - name: make the fisherman directory
      file:
        path="{{ ansible_env.HOME }}/.config/fish/functions"
        state=directory
        owner="{{ ansible_env.USER }}"
        mode=0755
        recurse=yes
    - name: install fisherman
      get_url:
        url="https://git.io/fisherman"
        dest="{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
#    - name: configure | change default shell
#      user: name="{{ ansible_env.USER }}" shell="/usr/local/bin/fish"
#      become: yes
    - name: git checkout dotfiles
      git:
        repo: 'https://github.com/mpppk/dotfiles.git'
        dest: dotfiles
