- hosts: wsl
  user: yuki
  vars:
    username: yuki
    email: niboshiporipori@gmail.com
    GOPATH: "{{ansible_env.HOME}}/go"
    go_get:
    - name: ghq
      url: github.com/motemen/ghq
    - name: fzf
      url: github.com/junegunn/fzf
    - name: hlb
      url: github.com/mpppk/hlb

  roles:
    - role: fubarhouse.golang
      become: yes
  tasks:
    - name: "apt-get install"
      apt: pkg={{item}} update_cache=yes
      become: yes
      with_items:
        - git
        - tig
        - tmux
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
    - git_config: name=user.name scope=global value="{{ username }}"
    - git_config: name=user.email scope=global value="{{ email }}"
    - git_config: name=core.editor scope=global value="vim"
    - name: install fish repo
      apt_repository:
        repo="ppa:fish-shell/release-2"
        state=present
        update_cache=yes
      when: ansible_distribution == "Ubuntu"
    - name: install fish
      apt: name=fish state=present
      become: yes
    - name: make the fisherman directory
      file:
        path="{{ ansible_env.HOME }}/.config/fish/functions"
        state=directory
        owner="{{ ansible_env.USER }}"
        mode=0755
        recurse=yes
    - name: install fisherman
      get_url:
        url="https://git.io/fisherman"
        dest="{{ ansible_env.HOME }}/.config/fish/functions/fisher.fish"
#    - name: configure | change default shell
#      user: name="{{ ansible_env.USER }}" shell="/usr/local/bin/fish"
#      become: yes
    - name: git checkout dotfiles
      git:
        repo: 'https://github.com/mpppk/dotfiles.git'
        dest: dotfiles
    - name: make the ghq directory
      file:
        path="{{ ansible_env.HOME }}/ghq"
        state=directory
        owner="{{ ansible_env.USER }}"
    - name: deploy.sh
      shell: "{{ansible_env.HOME}}/dotfiles/deploy.fish"
    - name: install fisherman plugins
      shell: "fish -c fisher"
    - name: Add docker GPG key
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - name: Add docker repository
      shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - name: "apt-get install docker"
      apt: pkg={{docker-ce}} update_cache=yes
      become: yes
