name: dotfiles test

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        echo $HOME
        ls -la
        pwd
        ./debian/install.sh $GITHUB_WORKSPACE
