name: dotfiles test

on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        ./debian/install.sh $GITHUB_WORKSPACE
  mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: install
      run: |
        ./mac/install.sh $GITHUB_WORKSPACE

